### PR TITLE
Standard deviation

### PR DESCRIPTION
**Pull request by mkbonini**
paired with Mary and Parker

### CODE REVIEW

**Comment by MaryT573** [comment]
Hey Mike, Love the standard deviation methods. But maybe remove the commented out code

**Review by MaryT573 — COMMENTED** [review]
Hi Mike. I removed the commented code

**Review by pdthomson — APPROVED** [review]
Looks much cleaner after taking out our comments

**Comment by pdthomson** [comment]
Code for tests and methods look great...APPROVED

**Pull request merged**
